ModLoader.SetupFileHook("lua/IMGUIGameEnd.lua", "lua/InfestedFixes/IMGUIGameEnd.lua", "replace" )
ModLoader.SetupFileHook("lua/IMScoringMixin.lua", "lua/InfestedFixes/IMScoringMixin.lua", "post")
ModLoader.SetupFileHook("lua/IMGUIMarineHUD.lua", "lua/InfestedFixes/IMGUIMarineHUD.lua", "replace")
ModLoader.SetupFileHook("lua/IMNS2Gamerules.lua", "lua/InfestedFixes/IMNS2Gamerules.lua", "replace")
ModLoader.SetupFileHook("lua/IMDeathMessage_Client.lua", "lua/InfestedFixes/IMDeathMessage_Client.lua", "replace")
ModLoader.SetupFileHook("lua/IMBalanceHealth.lua", "lua/InfestedFixes/IMBalanceHealth.lua", "replace")
ModLoader.SetupFileHook( "lua/TeamDeathMessageMixing.lua", "lua/IMTeamDeathMessageMixing.lua", "replace" )